services:
  3xui:
    image: ghcr.io/mhsanaei/3x-ui:v2.8.7
    restart: unless-stopped
    ports:
      - "127.0.0.1:2053:2053"
      - "32000-32100:32000-32100"
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_ENABLE_FAIL2BAN=true
    volumes:
      - ./x-ui-data:/etc/x-ui
