services:
  syncthing:
    image: syncthing/syncthing
    volumes:
      - ./syncthing-data:/var/syncthing
    environment:
      - STGUIADDRESS=https://0.0.0.0:8384
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
